version: "3.6"
volumes:
  shared-workspace:
    name: "Hadoop_Distributed_File_System"
    driver: local
services:
  jupyterlab:
    build: ./build/docker/jupyterlab/
    ports:
      - "8888:8888"
    volumes:
      - ./data:/opt/app/data
    entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root'

  namenode:
    image: cploutarchou/hadoop-base:namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./conf/hadoop/hadoop.env

  datanode:
    image: cploutarchou/hadoop-base:datanode
    container_name: datanode
    restart: always
    volumes:
      - ./hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./conf/hadoop/hadoop.env

  resourcemanager:
    image: cploutarchou/hadoop-base:hadoop-nodemanager
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./conf/hadoop/hadoop.env

  nodemanager:
    image: cploutarchou/hadoop-base:hadoop-nodemanager
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./conf/hadoop/hadoop.env

  historyserver:
    image: cploutarchou/hadoop-base:history-server
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - ./hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./conf/hadoop/hadoop.env


